"""
fastapi_server.py — HTTP wrapper around agent.py for the chatbot frontend.

Folder layout:
    repo/
    ├── agent_final/
    │   ├── agent.py          ← all agent logic lives here
    │   └── charts/           ← PNGs saved here by render_chart()
    └── backend/
        └── init_adk_server/
            └── fastapi_server.py   ← this file

Run from repo/backend/init_adk_server/:
    uv run uvicorn fastapi_server:app --host 0.0.0.0 --port 5000 --reload

Or from the repo root:
    uv run uvicorn backend.init_adk_server.fastapi_server:app --host 0.0.0.0 --port 5000 --reload
"""

import os
import re
import sys

# ---------------------------------------------------------------------------
# Path fix — add repo/agent_final/ to sys.path so "from agent import ..."
# resolves correctly regardless of where uvicorn is launched from.
# ---------------------------------------------------------------------------
_THIS_FILE   = os.path.dirname(os.path.abspath(__file__))          # repo/backend/init_adk_server
_REPO_ROOT   = os.path.abspath(os.path.join(_THIS_FILE, "../../")) # repo/
_AGENT_DIR   = os.path.join(_REPO_ROOT, "agent")             # repo/agent_final/

if _AGENT_DIR not in sys.path:
    sys.path.insert(0, _AGENT_DIR)

# Charts are saved by render_chart() into agent_final/charts/
# We serve that same folder as static files.
_CHART_DIR = os.path.join(_AGENT_DIR, "charts")
os.makedirs(_CHART_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# Imports (agent import MUST come after sys.path fix above)
# ---------------------------------------------------------------------------
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from agent import process_payload  # noqa: E402  (intentional late import)

# ==============================================================================
# App setup
# ==============================================================================
app = FastAPI(title="Supermarket Inventory Chatbot API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten in production
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve agent_final/charts/ at /charts
# e.g. agent_final/charts/foo.png → http://adk-agent:5000/api/agent/charts/foo.png
app.mount("/charts", StaticFiles(directory=_CHART_DIR), name="charts")

# ==============================================================================
# In-memory conversation store
# { session_id: [ ChatMessage, ... ] }
# session_id is generated by the browser on page load and sent with every request.
# Refreshing the page generates a new session_id → fresh history.
# ==============================================================================
conversation_store: dict[str, list] = {}


# ==============================================================================
# Pydantic models
# ==============================================================================
class ChatRequest(BaseModel):
    session_id: str   # browser-generated UUID, reset on page refresh
    message: str      # raw user input text


class ChatMessage(BaseModel):
    role: str               # "user" or "assistant"
    content: str            # display text
    image_url: str | None   # chart URL for DATA_VISUAL turns, else None


class ChatResponse(BaseModel):
    session_id: str
    response: str             # assistant text
    image_url: str | None     # browser-accessible chart PNG URL, or None
    base64: str | None        # base64-encoded PNG chart, or None
    recommendation: dict | None  # { product_name, supplier_name, qty } or None
    intent: str               # STOCK_ORDER | DATA_VISUAL | GENERAL | REJECTED | ERROR
    history: list[ChatMessage]


# ==============================================================================
# Helpers
# ==============================================================================
_API_BASE = "http://adk-agent:5000/api/agent"

def extract_image_url(agent_result: dict) -> str | None:
    """
    render_chart() saves PNGs to agent_final/charts/ and the ADK agent
    embeds the path in its message as markdown:
        ![Title](./charts/foo_20260610_123456.png)

    Extract the filename and return a browser-accessible URL.
    """
    message = agent_result.get("message", "")

    # Primary: markdown image embed
    match = re.search(r'!\[.*?\]\(\./charts/([^)]+)\)', message)
    if match:
        return f"{_API_BASE}/charts/{match.group(1)}"

    # Fallback: bare path anywhere in the message text
    match = re.search(r'charts[/\\]([^\s"\']+\.png)', message)
    if match:
        return f"{_API_BASE}/charts/{match.group(1)}"

    return None


def clean_message_text(message: str) -> str:
    """Strip the markdown image embed — frontend renders the image via image_url."""
    return re.sub(r'!\[.*?\]\(\./charts/[^)]+\)', '', message).strip()


# ==============================================================================
# POST /chat
# ==============================================================================
@app.post("/api/agent/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    # Initialise history for new sessions
    if req.session_id not in conversation_store:
        conversation_store[req.session_id] = []

    history = conversation_store[req.session_id]

    # 1. Record user turn
    history.append(ChatMessage(role="user", content=req.message, image_url=None))

    # 2. Run the agent
    result = process_payload({"input_text": req.message})

    # 3. Resolve intent label
    #    process_payload returns different shapes depending on the branch:
    #      STOCK_ORDER → { message, recommendation }            (no "intent" key)
    #      DATA_VISUAL → { status, intent, message, input_text }
    #      GENERAL     → { status, intent, message, input_text }
    #      REJECTED    → { status, reason, message }
    #      ERROR       → { status, message }
    intent = result.get("intent", "UNKNOWN")
    if result.get("status") == "rejected":
        intent = "REJECTED"
    elif result.get("status") == "error":
        intent = "ERROR"
    elif "recommendation" in result:
        intent = "STOCK_ORDER"

    # 4. Extract text
    response_text = result.get("message", "Sorry, I could not process that request.")

    # 5. Extract chart: base64 from agent, image_url from file path
    image_url = None
    base64_img = result.get("base64", None)
    recommendation = result.get("recommendation", None)
    if intent == "DATA_VISUAL":
        if not base64_img:
            image_url = extract_image_url(result)
        response_text = clean_message_text(response_text)

    # 6. Record assistant turn
    history.append(ChatMessage(role="assistant", content=response_text, image_url=image_url))

    return ChatResponse(
        session_id=req.session_id,
        response=response_text,
        image_url=image_url,
        base64=base64_img,
        recommendation=recommendation,
        intent=intent,
        history=history,
    )


# ==============================================================================
# GET /health
# ==============================================================================
@app.get("/api/agent/health")
def health():
    return {"status": "ok"}


# ==============================================================================
# GET /history/{session_id}
# ==============================================================================
@app.get("/api/agent/history/{session_id}")
def get_history(session_id: str):
    return {
        "session_id": session_id,
        "history": conversation_store.get(session_id, []),
    }


# ==============================================================================
# DELETE /history/{session_id}
# ==============================================================================
@app.delete("/api/agent/history/{session_id}")
def clear_history(session_id: str):
    conversation_store.pop(session_id, None)
    return {"session_id": session_id, "cleared": True}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("fastapi_server:app", host="0.0.0.0", port=5000, reload=True)